# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20170525_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='text',
            field=models.TextField(max_length=400),
        ),
    ]
