# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170419_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Генерация ссылки'),
        ),
    ]
