# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20170603_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
    ]
